repository:
  url                       : https://github.com/yourusername/yourbookrepo  # Online location of your book
  path_to_book              : path/to/book  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  notebook_interface: "classic"  # "classic" or "jupyterlab"
execute:
  execute_notebooks: auto
